### ISSUE TITLE
Does this still work ?

### ISSUE THREAD

**Issue by bertbeck** [wiredprairie/unofficial_nodejs_nest#17]
Just tried a simple login test with the nodejs code. It returns login failed for my account.

**Comment by wiredprairie** [comment]
Not sure. I don't use nest thermostats any longer so hopefully someone else can comment.

**Comment by bertbeck** [comment]
what thermostat do you use ? I'm a little disappointed with the nest. I
have started using wireless sensor tags - very good stuff - wish they had a
thermostat

**Comment by wiredprairie** [comment]
Ecobee

bertbeck wrote:

> what thermostat do you use ? I'm a little disappointed with the nest. I
> have started using wireless sensor tags - very good stuff - wish they 
> had a
> thermostat
>

**Comment by watou** [comment]
> Ecobee

Excellent choice!

**Comment by cmcoffman** [comment]
It still works, I just tried it.
